# Generated by Django 5.2.3 on 2026-06-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='contactcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contactcategory',
            name='icon',
            field=models.CharField(blank=True, default='bx-user', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='contactcategory',
            name='owner',
        ),
    ]
