# Generated by Django 5.2.3 on 2026-06-14 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='cleave-blue', max_length=20)),
                ('mode', models.CharField(default='light', max_length=10)),
                ('compact_layout', models.BooleanField(default=False)),
                ('large_text', models.BooleanField(default=False)),
                ('reduced_motion', models.BooleanField(default=False)),
                ('high_contrast', models.BooleanField(default=False)),
                ('language', models.CharField(default='en', max_length=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('settlement_reminders', models.BooleanField(default=True)),
                ('expense_updates', models.BooleanField(default=True)),
                ('group_activity', models.BooleanField(default=True)),
                ('weekly_summary', models.BooleanField(default=False)),
                ('monthly_summary', models.BooleanField(default=True)),
                ('ai_insights', models.BooleanField(default=True)),
                ('spending_alerts', models.BooleanField(default=False)),
                ('budget_recommendations', models.BooleanField(default=False)),
                ('smart_suggestions', models.BooleanField(default=True)),
                ('profile_visibility', models.CharField(default='members', max_length=15)),
                ('phone_visibility', models.CharField(default='members', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
    ]
