# Generated by Django 5.2.3 on 2026-06-14 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_options_and_more'),
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='expenses.expense'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('ignored', 'Ignored')], default='pending', max_length=15),
        ),
    ]
